### ISSUE TITLE
Problem publising from Bot composer

### ISSUE THREAD

**Issue by michaelstiben** [MicrosoftDocs/composer-docs#13] opened 2020-10-06 23:39 UTC
I was publishing the first example. I already tested in Bot emulator Framework and it worked like a charm. However, after the deployment of the services in azure, which were deployed successfully, I fill the publishing profile with the text retrieved from the deploy script and the next error log is raised: 

```
{
  "status": "DEPLOY_ERROR",
  "message": "{\"stack\":\"TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters\\n    at new ClientRequest (_http_client.js:139:13)\\n    at request (https.js:309:10)"
}
```

**Comment by zxyanliu** [comment] 2020-10-06 23:45
Hi, thanks for reporting the issue.
Can you provide more details such as what version of Composer did you use? Where did you publish the bot to? Which doc did you follow for this process?

**Comment by zxyanliu** [comment] 2020-10-07 16:08
@michaelstiben 
I am wondering if you followed [this doc](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)?

**Comment by michaelstiben** [comment] 2020-10-09 20:52
Thanks @zxyanliu  for you help.

Yes, I was following [this doc](https://docs.microsoft.com/en-us/composer/how-to-publish-bot).  I manually deploy the services and manually generate the accessToken as is said [here](https://docs.microsoft.com/en-us/composer/how-to-publish-bot#deploy-to-existing-azure-resources). Also, I manually create the database and the collection in cosmos and the container in the blob storage.

![image](https://user-images.githubusercontent.com/41975874/95629737-259d8200-0a46-11eb-9826-f943ebdfe421.png)

I'm using Bot Composer 1.1.1 software. Also I tried building the composer on my side but the result was the same.

I'm gonna to copy the full error log message, it could be useful. 

```
Publish starting...
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\MichaelStibenParedes\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\d2a5fbe7c6f466d448f0d9404752d206\\azurewebapp\\ComposerDialogs\\generated\\interuption\\echo.es-es.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\MichaelStibenParedes\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\d2a5fbe7c6f466d448f0d9404752d206\\azurewebapp\\ComposerDialogs\\generated\\interuption\\echo.es-mx.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Creating LUIS.ai application: Bots – MSDN(dev)-echo.es-es.lu version:0.1\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Creating LUIS.ai application: Bots – MSDN(dev)-echo.es-mx.lu version:0.1\n"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"stack\":\"TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters\\n    at new ClientRequest (_http_client.js:139:13)\\n    at request (https.js:309:10)\\n    at C:\\\\Users\\\\MichaelStibenParedes\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\node-fetch\\\\lib\\\\index.js:1432:15\\n    at new Promise (<anonymous>)\\n    at Function.fetch [as default] (C:\\\\Users\\\\MichaelStibenParedes\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\node-fetch\\\\lib\\\\index.js:1401:9)\\n    at LuBuildCore.importApplication (C:\\\\Users\\\\MichaelStibenParedes\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\@microsoft\\\\bf-lu\\\\lib\\\\parser\\\\lubuild\\\\core.js:90:58)\\n    at Builder.createApplication (C:\\\\Users\\\\MichaelStibenParedes\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\@microsoft\\\\bf-lu\\\\lib\\\\parser\\\\lubuild\\\\builder.js:333:44)\\n    at async C:\\\\Users\\\\MichaelStibenParedes\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\@microsoft\\\\bf-lu\\\\lib\\\\parser\\\\lubuild\\\\builder.js:178:47\\n    at async Promise.all (index 0)\\n    at async Builder.build (C:\\\\Users\\\\MichaelStibenParedes\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\@microsoft\\\\bf-lu\\\\lib\\\\parser\\\\lubuild\\\\builder.js:155:17)\",\"message\":\"Request path contains unescaped characters\",\"code\":\"ERR_UNESCAPED_CHARACTERS\"}"
}
Request path contains unescaped characters
```

**Comment by zxyanliu** [comment] 2020-10-29 22:15
Hi, the publishing experience is going to be updated for R11 release (Nov), and docs will be updated accordingly.
Hopefully, the issues regarding publishing will all be addressed.

**Comment by zxyanliu** [comment] 2020-11-16 22:12
Hey please try the process with [the most recent Composer](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.2.0) and follow the doc.

**Comment by zxyanliu** [comment] 2020-11-24 20:23
Closing this issue for now since it was not reproduced with [the most recent version of Composer](https://github.com/microsoft/BotFramework-Composer/releases/latest).

**Closed by zxyanliu** 2020-11-24 20:23 UTC
Labels: topic: publish
