### ISSUE TITLE
How to switch directories

### ISSUE THREAD

**Issue by juanfergc** [MicrosoftDocs/composer-docs#86] opened 2021-01-18 21:26 UTC
How can I switch to another directory in order to select a different subscription where my resources will be deployed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot#login-to-azure)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment] 2021-01-30 21:45
Duplicate of #91.
Closing this one.

**Closed by zxyanliu** 2021-01-30 21:45 UTC
