### ISSUE TITLE
Provision failure when creating azure resources

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#73] opened 2020-12-28 20:29 UTC
Following the documentation to publish my bot. After loging in to my work account, selecting the options to Publish Bot ao Azure Web App, Create New Resource, adding the requested information and accepting the default options, when I click "Done" I get an error saying "Provision Failure - Error when provision target".

![Captura de ecrã 2020-12-28 202918](https://user-images.githubusercontent.com/42462/103241530-658c4b00-494b-11eb-8519-43aa6f5f3c7a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment] 2020-12-28 20:31
Yeah, this is a known issue. See: https://github.com/microsoft/BotFramework-Composer/issues/5335

**Comment by zxyanliu** [comment] 2020-12-28 20:35
The fixing PR to this issue has been merged to the main branch, but I am not sure if the fix was taken into the electron distribution at this point.

To unlock you, you might consider installing the most recent [nightly build](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.0-nightly.197726.34631bf)? I can test the publish functionality of the nightly-build version for you later today if you want. 

I apologize for the inconvenience.

**Comment by tiagonmas** [comment] 2020-12-28 20:50
downloading the nightly build and will test. thanks

**Comment by tiagonmas** [comment] 2020-12-28 21:00
same error with the nightly build 34631bf 
<img width="950" alt="BotError" src="https://user-images.githubusercontent.com/42462/103242853-a38b6e00-494f-11eb-9496-725e09809f71.png">

**Comment by zxyanliu** [comment] 2020-12-28 21:11
FYI. I am testing the nightly build for you and will try to get the best possible solution I can for you today.

**Comment by zxyanliu** [comment] 2020-12-28 21:50
FYI. I was able to provision Azure resources and publish an echo bot using [v1.3.0-nightly.197726.34631bf](
https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.0-nightly.197726.34631bf). 

**Tip:**
If you fail on your end, consider uninstalling your previous Composer version before installing a newer Composer version. 

![image](https://user-images.githubusercontent.com/32497439/103244762-de22e580-4912-11eb-9364-8d3910be879b.png)

![image](https://user-images.githubusercontent.com/32497439/103244823-10344780-4913-11eb-904e-708107269712.png)

![image](https://user-images.githubusercontent.com/32497439/103244902-4376d680-4913-11eb-9f53-cbe43e6b177d.png)

**Comment by tiagonmas** [comment] 2020-12-29 09:36
Uninstalled composer. Restarted PC. Installed new nightly build [da63bc9](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.0-nightly.198406.da63bc9), created a Echo Bot, published and still got the same error. Any way to debug the error ?
![BotError2](https://user-images.githubusercontent.com/42462/103274289-357b9100-49b9-11eb-82c3-67d79f6074fa.png)

**Comment by zxyanliu** [comment] 2021-01-01 05:54
This is wired...I will try again and let you know after the holiday break. Thanks for your patience.

**Comment by ryan-daly-AgFCS** [comment] 2021-01-11 19:42
I was seeing this issue to on 1.3 when trying to provision to existing resources. I'll test again once my other bug is resolved and I upgrade from 1.2.1.

**Comment by tiagonmas** [comment] 2021-01-12 20:26
Just tried it again with the lates nightly build 4064ed8. No luck! Same error "Provision failure". Any news on solving this ?

**Comment by zxyanliu** [comment] 2021-01-12 21:20
Hi @tiagonmas unfortunately, I was unable to reproduce your error. 
But I referenced your issue here, just FYI. https://github.com/microsoft/BotFramework-Composer/issues/5467

**Comment by tiagonmas** [comment] 2021-01-12 22:28
Happy to share any more logs or connect internally if it helps solve the issue !?

**Comment by tiagonmas** [comment] 2021-01-13 10:21
Happy to share any more logs or connect internally if it helps solve the issue !?

**Comment by tiagonmas** [comment] 2021-01-16 22:16
Just tried with nightly  13.1-nightly 202832.2d28769 and same issue 👎

**Comment by yeze322** [comment] 2021-01-20 04:18
@VanyLaw

**Comment by zxyanliu** [comment] 2021-01-20 16:55
@tiagonmas Thanks again for your patience. Our developers are working actively on solving this issue.

**Comment by MeenakshiBalekar** [comment] 2021-01-21 14:16
I am also facing same issue :

![image](https://user-images.githubusercontent.com/58509122/105362746-45d20500-5c21-11eb-9aaa-b533db2e2b83.png)
Please help to resolve same 
Bot composer version : V1.3.0

**Comment by tiagonmas** [comment] 2021-01-21 14:29
@MeenakshiBalekar Take a look at issue https://github.com/microsoft/BotFramework-Composer/issues/5467

**Comment by zxyanliu** [comment] 2021-02-12 00:02
Please try the following version of Composer. 
https://github.com/microsoft/BotFramework-Composer/releases/latest

**Comment by zxyanliu** [comment] 2021-02-12 19:22
Closing this issue as it has been addressed. Thanks!

**Closed by zxyanliu** 2021-02-12 19:22 UTC
Labels: source: microsoft internal, topic: publish

**Comment by orcelik** [comment] 2021-03-25 17:09
This issue still persists in version 1.4.0.

**Comment by Benjiiim** [comment] 2021-04-02 13:47
Using the following env variable is working with 1.4.0 when using the Electron version:

NODE_OPTIONS="--max-http-header-size=16000"
