### ISSUE TITLE
Publishing a bot - Login to Azure only allows Work or school

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#72] opened 2020-12-28 20:17 UTC
I want to deploy my bot to my personal Azure subscription and in step 5 of "Login to Azure", if I enter my personal account I get "We couldn't find a work or school account with that email address.". If I create the resources on my own, and provide the Id's I'm sure I'll be able to make it work !? why the limitation to work/school ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment] 2020-12-28 20:28
Hi, that's a great point to bring up. We will get this confirmed with our developers working on the publishing functionality and get back to you later. FYI. Due to the holiday season, most developers will come back to work around early January.  

Thanks again for your feedback!

**Comment by zxyanliu** [comment] 2021-01-05 00:21
FYI. This is a duplicate of this issue: https://github.com/microsoft/BotFramework-Composer/issues/5393

**Comment by zxyanliu** [comment] 2021-02-11 23:28
Hi, sorry about my late response.
I think "If you are trying to login with a personal Microsoft account (non-work / school) then authentication will not work."
See parent: https://github.com/microsoft/BotFramework-Composer/issues/5456#issuecomment-755565203

**Comment by zxyanliu** [comment] 2021-02-12 00:01
Closing this issue as it is answered.

**Closed by zxyanliu** 2021-02-12 00:01 UTC
Labels: duplicate, known issue, source: microsoft internal, topic: publish

**Comment by zxyanliu** [comment] 2021-03-10 17:28
FYI. Login to Azure with the personal account is now supported in https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.1-nightly.221713.7f02df0
