### ISSUE TITLE
More information on Multi choice input

### ISSUE THREAD

**Issue by tiagonmas** [MicrosoftDocs/composer-docs#82] opened 2021-01-06 11:54 UTC
The [Multi Choice input section ](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input#multiple-choice-input) does not mention anything about the several options that the composer presents in the User Input tab. For example, there are several options for Array of choices, what do they mean (simple, structured, expression)?  How do we use each option ?

There are also several "choice options" (inline seprator, inline or, inline or more, etc). What are these for ?

Would also be great to understand how we can set the options in a dynamic way, based out of a property, or a result of a previous call.

Thanks,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce92ad12-27d2-3e3c-5a25-122cfc002837
* Version Independent ID: 52b6a9f0-2bf1-56e1-4044-54b89e69b81e
* Content: [Ask for user input - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input)
* Content Source: [composer-docs/how-to-ask-for-user-input.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-ask-for-user-input.md)
* Service: **bot-composer**
* GitHub Login: @WashingtonKayaker
* Microsoft Alias: **kamrani**

**Comment by tiagonmas** [comment] 2021-01-12 20:14
Hi, any news ? where can I get more info on this ? thanks

**Comment by tiagonmas** [comment] 2021-01-17 15:38
ping ?

**Comment by tiagonmas** [comment] 2021-01-25 19:39
ping ?

**Comment by zxyanliu** [comment] 2021-01-27 01:02
@tiagonmas FYI.

I provided some basic instructions in [this similar thread](https://github.com/MicrosoftDocs/composer-docs/issues/89#issuecomment-767934560).

**Comment by tiagonmas** [comment] 2021-02-04 14:07
not sure how it relates to my question. there should be clear indication of what each composer entries mean  (simple, structured, expression)... the other thread did not answer my doubt, it least in a simple manner. thanks

**Comment by zxyanliu** [comment] 2021-02-24 06:17
Hi, this is a duplicate of https://github.com/MicrosoftDocs/composer-docs/issues/98. 
The PR to address this issue is in review.

**Comment by zxyanliu** [comment] 2021-03-09 22:30
The content has been updated and merged and will go live soon.
Closing this issue for now. Thanks!

**Closed by zxyanliu** 2021-03-09 22:30 UTC
Labels: duplicate, source: microsoft internal, status: work in progress
