### ISSUE TITLE
Cannot build composer from source 

### ISSUE THREAD

**Issue by Khanh-Ngy** [MicrosoftDocs/composer-docs#78] opened 2021-01-04 06:30 UTC
I tried this : https://docs.microsoft.com/en-us/composer/install-composer#build-composer-from-source

But got problems when run **yarn**  at terminal in ...\BotFramework-Composer\Composer
![image](https://user-images.githubusercontent.com/71876037/103506824-3ff1cb00-4e90-11eb-8ec8-bb0563d940ef.png)
It didn't run anymore...

Then , I tried other way with running **yarn install** && **yarn build**
![image](https://user-images.githubusercontent.com/71876037/103507063-d625f100-4e90-11eb-931b-d5393466f497.png)

**Comment by zxyanliu** [comment] 2021-01-04 20:11
Hi @Khanh-Ngy thanks for reporting the issue.
Can you please check you have met all the [prerequisites](https://docs.microsoft.com/en-us/composer/install-composer#prerequisites-for-building-composer-from-source) documented in the [installation article](https://docs.microsoft.com/en-us/composer/install-composer)? 

Git
Node.js. Use version 12.13.0 or later.
The latest stable release of Yarn.
The Bot Framework Emulator.
The .NET Core SDK 3.1 and above.

**Comment by zxyanliu** [comment] 2021-01-04 20:17
I am closing this issue since it's a duplicate of https://github.com/microsoft/BotFramework-Composer/issues/5435

**Closed** 2021-01-04 23:22 UTC
Labels: duplicate, source: customer, status: work in progress

**Comment by zxyanliu** [comment] 2021-01-04 23:27
Please make sure you use the correct [Node.js](https://nodejs.org/) versions: use the latest LTS 14.x or 12.x release line.
